acmucsd/membership-portal-ui

package.json, yarn.lock
should we use prettier or do we just want to use eslint but in either case we should add a precommit
=> Add prettier and husky precommit

config-overrides.js, package.json, yarn.lock
Finished the rest of boilerplate documentation at https://ant.design/docs/react/use-with-create-react-app
=> updated packages and boilerplate (Closes #8)

package.json, src/index.js, src/reducers/TempReducer.js, src/reducers/index.js, src/store.js, yarn.lock
I made a temporary reducer but not sure if that's the right way of doing this. Never set up redux without any reducers before but we probably won't get to making reducers for a while
=> Set up Redux

.travis.yml, README.md, package.json, tests/reducers/TempReducer.test.js, yarn.lock
=> Set up travis and coveralls (Closes #9)

src/components/NavBarHorizontal/NavTileItem/index.jsx, src/components/NavBarHorizontal/NavTileItem/style.less, src/components/NavBarHorizontal/index.jsx, src/components/NavBarHorizontal/style.less, src/components/NavBarVertical/index.jsx, src/components/NavDropdown/index.jsx, src/components/NavListItem/index.jsx, src/components/NavListItem/style.less
=> Add horizontal navbar

src/components/PasswordForm/index.jsx, src/components/PasswordForm/style.less, src/styles/vars.less
Created a temporary password reset or else 'Forgot Password' would hyperlink to a blank page - I'll pr the log in page after this gets approved
Looks like: https://i.imgur.com/MRGIavg.png
=> Temporary Password Reset 

src/components/TopLeaderCard/index.jsx, src/components/TopLeaderCard/style.less, src/containers/LeaderPage.jsx
Card component for top three on leaderboard
=> Leaderboard Top Card Component

src/components/RegisterForm/index.jsx, src/containers/PasswordPage.jsx, src/index.js
Completed the hyperlink to the temporary 'Forgot your password'
Looks like: https://i.imgur.com/LAdTRvv.png
Also do you want the logo to hyperlink to anything? https://i.imgur.com/eLK1MzX.png
=> Created temp forgot password page

src/actions/eventsActions.js, src/actions/types.js, src/components/EventCheckIn/index.jsx, src/containers/EventCheckIn.jsx, src/reducers/EventsReducer.js, src/reducers/index.js
Still needs to make a call to the backend before we can close #51
=> Add Event CheckIn Container

src/components/Banner/style.less
Current: https://i.imgur.com/m0vd3Sv.png
Fix: https://i.imgur.com/0b1VSTJ.png
=> Update banner size

src/components/Banner/style.less, src/components/ProfileUpdate/index.jsx, src/components/ProfileUpdate/style.less, src/styles/vars.less
=> Update profile component

src/components/AuthenticateCard/index.jsx, src/components/AuthenticateCard/style.less, src/containers/AuthPage.jsx, src/index.js
=> Authenticate card and container 

src/components/AdminPage/index.jsx, src/components/AdminPage/style.less, src/components/CreateEventForm/index.jsx, src/components/CreateEventForm/style.less, src/containers/AdminPage.jsx, src/index.js, src/reducers/AuthReducer.js, src/styles/vars.less
Not mobile responsive but we don't even have a way to access admin on mobile yet.
=> Add create events form

src/components/AdminPage/index.jsx, src/components/CreateEventForm/index.jsx, src/components/CreateEventForm/style.less, src/containers/CreateEventForm.jsx
Need to also set up form validation with yup. Will do in a later PR.
=> Connect admin form to Formik

src/components/RegisterForm/index.jsx, src/containers/RegisterForm.jsx
Values are supposed to be integers not booleans
=> Fix register value bug

src/actions/authActions.js, src/utils/storage.js
Shout out to my friends at ACM @ UCLA but also we should figure out a better method of storage
=> Add token storage (Closes #76)

src/containers/FourAndMore.jsx, src/containers/TopThree.jsx, src/utils.js
Temporary fix until we actually add profile pics
=> Randomly generate leaderboard profile pic

src/containers/RegisterForm.jsx
technically it was a feature not a bug
=> Removed resetForm()

src/components/EventCheckIn/index.jsx, src/containers/EventCheckIn.jsx
idk if this is the right way but its the fastest because our input and submit button isnt wrapped in a form
=> Event Check in Form handing Enter Key (Closes #129)

src/components/PasswordForm/index.jsx, src/components/PasswordForm/style.less, src/components/PasswordReset/index.jsx, src/components/PasswordReset/style.less, src/containers/PasswordUpdate.jsx, src/index.js, src/styles/vars.less
Commented out the onchange and values because container is in a separate pr
=> Password Reset Layout

src/components/ProfileCard/index.jsx
- Turned level -> lvl
- Mod issue with exp
=> Minor Fixes for Profile Card

src/containers/CreateEventForm.jsx
Fixes #145: a 12th hour bug where midnight gets cast to noon and noon gets cast to midnight.
=> fixed edge case with 12th hour

src/components/PageLayout/style.less
<b>Fixes this horizontal scrollbar:</b> <img src="https://i.imgur.com/uDt5xkq.png" />
=> HR Fixes Horizontal Scrollbar

src/containers/PasswordUpdate.jsx
Accidentally removed this idk y - you need it to fire off actions - password reset should be officially done after this pr is merged
=> Adds Prevent Default

src/components/EventCard/index.jsx
prevent non admins from seeing the edit link
=> No public editing allowed

src/actions/profileActions.js, src/components/ProfileUpdate/index.jsx, src/components/ProfileUpdate/style.less, src/containers/ProfileUpdate.jsx, src/reducers/ProfileReducer.js
Can now update profile
Responsive views (probably)
Form is auto filled with current user information
Users notified about update profile status
=> Edit Profile Page updated

src/actions/authActions.js, src/actions/eventsActions.js, src/components/EditEventForm/index.jsx, src/config.js, src/containers/EditEventForm.jsx, src/containers/NavProfile.jsx, src/containers/requireAdminAuth.jsx, src/containers/requireAuth.jsx, src/index.js, src/reducers/AuthReducer.js
Admin pages to be seen only by admins now
- removed other comments
- Stopping some useEffect calls to update constantly when only needing to update once (fetchUser sometimes)
=> Require admin auth

src/actions/eventsActions.js, src/components/EventCheckIn/index.jsx, src/components/EventCheckIn/style.less, src/containers/EventCheckIn.jsx
- Added checkbox to check off if you are staff
- box visible only to STAFF members
=> Staff Check In

package-lock.json, package.json, src/actions/profileActions.js, src/components/NavProfile/index.jsx, src/components/ProfileCard/index.jsx, src/components/ProfilePage/index.jsx, src/components/ProfileUpdate/index.jsx, src/components/ProfileUpdate/style.less, src/config.js, src/containers/FourAndMore.jsx, src/containers/NavProfile.jsx, src/containers/ProfileCard.jsx, src/containers/TopThree.jsx, src/reducers/LeaderboardReducer.js, src/reducers/UserReducer.js
Allows users to edit their profile picture
Requires the backend merge first
=> Profile uploads

src/components/EventCard/index.jsx, src/components/EventCard/styles.less, src/styles/vars.less
=> Home Page: Fixed H2 Text Overlap (Closes #132)

src/components/ErrorPage/index.jsx
=> Typo in 404 Page

package-lock.json, package.json, src/containers/egg/BreadPage/index.jsx, src/containers/egg/BreadPage/style.less, src/index.js
=> Secret bread

src/components/admin/AwardPointsForm/index.jsx, src/containers/admin/AwardPointsForm.jsx
Makes it not so easy to award points twice by accident
Addresses #215
=> Safe guard award points form

src/components/EditEventForm/index.jsx, src/components/EditEventPage/index.jsx, src/components/admin/CreateEventForm/index.jsx, src/containers/admin/CreateEventForm.jsx, src/containers/admin/EditEventForm.jsx, src/containers/admin/EditEventPage.jsx, src/index.js
Stored as committee in database. Lets people fill in a committee part with a string
Addresses #186
=> Add comittee/org field in event form

src/config.js
Hope this is the intended implementation.
Resolves #220
=> Use Dev Backend on Heroku

src/components/LeaderListItem/index.jsx, src/components/LeaderListItem/style.less
Positions rank below name for thinner screens and is ready to contain badges.
Resolves #195
=> Use Dynamic Leaderboard Layout

package.json
no idea why its been antd-demo for the past year
=> Package.json rename ant-demo -> membership-portal-ui

src/components/ProfileCard/index.jsx
=> Clickable Profile Card

src/components/NavProfile/index.jsx
Attached popover to parent component.
Resolves #90
=> Prevent Popup Menu from Scrolling

src/components/EventCard/index.jsx, src/components/EventCard/styles.less, src/utils.js
Added two new helper utils and updated the event card.
Resolves #224
=> Make Online Locations Clickable

src/components/EditEventForm/index.jsx
=> Added event handler for discard button

package-lock.json, package.json, yarn.lock
* added husky and lint staged; included in npm and yarn locks
* set up pre-commit action in package.json
Resolves #227
=> Automatically Lint Staged Files on Commit

package-lock.json, package.json, yarn.lock
Reverts acmucsd/membership-portal-ui#255
Resolves #259
=> Revert "Automatically Lint Staged Files on Commit"

.eslintrc.js, package-lock.json, src/actions/adminActions.js, src/actions/authActions.js, src/actions/profileActions.js, src/actions/userActions.js
Fixes admin functionality and broken package lock file. I restored the actions to their pre-linted state and ignored the nested promise error for now. I tested the broken actions and they're working again. We'll want to revisit the actions at a later time and determine the best use of dispatch and error handling, because there's currently a mix of strategies in place for error handling and returning data.
=> Restore Promises and Fix Package Lock

src/components/PasswordForm/index.jsx, src/components/PasswordForm/style.less, src/containers/PasswordPage.jsx
Closes #270.
Adds a button to submit the password request form. Button is similar in layout with the event check-in button.
=> Add button to Password Request

package-lock.json, package.json, src/components/DiscordPage/index.jsx, src/components/DiscordPage/style.less, src/components/NavBarHorizontal/index.jsx, src/components/NavBarVertical/index.jsx, src/components/NavDropdown/index.jsx, src/containers/DiscordPage.jsx, src/index.js
Switch to using Discord's widget rather than taking the user outside of the website on navigation click.
=> Use Discord's Widget

src/components/ProfileUpdate/index.jsx, src/components/RegisterForm/index.jsx, src/containers/RegisterForm.jsx
Closes #180.
Adds state set for ProfileUpdate component to reflect client-side change, as well as changing properties of component.
=> Graduation Year update visual bug

src/actions/types.js, src/components/Banner/index.jsx, src/config.js
I switched it to have a mobile banner file (126kb) and regular banner file (395kb). This should help optimize site loading and the amount of data used.
=> Use Dynamic Banner Sizes

package-lock.json, package.json, src/actions/types.js, src/components/Banner/index.jsx, src/components/DiscordPage/index.jsx, src/components/DiscordPage/style.less, src/components/EventCard/styles.less, src/components/NavBarHorizontal/index.jsx, src/components/NavBarVertical/index.jsx, src/components/NavDropdown/index.jsx, src/components/PasswordForm/index.jsx, src/components/PasswordForm/style.less, src/components/ProfileUpdate/index.jsx, src/components/RegisterForm/index.jsx, src/config.js, src/containers/DiscordPage.jsx, src/containers/PasswordPage.jsx, src/containers/RegisterForm.jsx, src/index.js
This release contains mostly feature additions and one bug fix.
- Replaced Discord link in sidebar with Discord widget (#286)
- Added submit button to password request (#289)
- Fixed bug where graduation year couldn't be updated when editing profile (#251)
- Banners on the portal homepage can now be resizable (#292)
- Fix event card image height to 150 pixels (#294)
Hey everyone! This week has been a slow one (finals incoming), but we've managed to get some stuff knocked out:
- The Discord link in the Membership Portal sidebar now links you to a slick Discord widget. It's light mode. I know Emily would be proud :3
- There's now a submission button in the password reset screen! You had to press "enter" before, if you didn't figure it out.
=> Nightly Merge - 1.1.3

src/actions/profileActions.js, src/components/ProfileUpdate/index.jsx
Update API url for profile uploads to match backend, since backend profile route was changed from `POST /profile` to `POST /profile/:uuid`
=> Update API url for profile uploads to match backend

.circleci/config.yml, README.md
Removes references to yarn and fixes CircleCI config.
=> Establish npm as Package Manager

src/actions/eventsActions.ts, src/components/admin/CreateEventForm/index.tsx, src/components/admin/CreateEventForm/style.less, src/containers/PastEvents.tsx
This PR adds a drop-down to the "Committee" entry of the Create Event form.
Additionally, this PR also fixes an API route change for attendances; the middleware
needed modification to account for a property change in the response of the
`GET api/v1/attendance` route.
=> Suborg dropdown in CreateEventForm

src/containers/CheckInModal.tsx
From `Please show this to a board member to enter the room!` to `Thanks for checking in!`
=> Changed Event Card Modal Message

package-lock.json, package.json, src/actions/eventsActions.ts
Add URI decoding to checkin code processing and bump version to 1.2.1.
=> Checkin Fix

package-lock.json, package.json, src/actions/authActions.ts, src/actions/registerActions.ts, src/components/RegisterForm/index.tsx, src/components/RegisterForm/style.less, src/components/SignInForm/index.tsx, src/components/SignInForm/style.less, src/containers/RegisterForm.tsx, src/containers/SignInForm.tsx
Checks the sign in and sign up form fields for valid values.
=> Form Validation

package-lock.json, package.json, src/components/EditEventForm/index.tsx, src/components/admin/CreateEventForm/index.tsx, src/components/admin/CreateEventForm/style.less, src/components/admin/EditEventForm/index.tsx, src/components/admin/EditEventForm/style.less, src/components/admin/EditEventPage/index.tsx, src/components/admin/EditEventPage/style.less, src/containers/admin/CreateEventForm.tsx, src/containers/admin/EditEventForm.tsx, src/containers/admin/EditEventPage.tsx, src/styles/vars.less
Added new date + time fields for event creation and editing. Added client-side validation to ensure all fields are filled in. Skipping use of Formik + Yum validation for now as it would require rewriting the form layout.
Resolves #350
=> Event Administration Updates

src/components/AboutPage/index.tsx
=> Fix Discord Link

package.json, yarn.lock
Set the wrong version for `react-router` and busted the site. Site is now unbusted.
=> Oopsie Woopsie

src/actions/authActions.ts, src/utils.ts
Displays message upon login, and doesn't disappear until user dismisses it. Idk why I couldn't get React to work in the authActions file, but I ended up doing it manually and it worked. Since it's a temporary thing, idk how important the code quality is 😅
=> Add Census Popup

src/containers/UpcomingEvents.tsx
Code was checkin the attendance uuid for a match rather than the actual event uuid.
=> Fix Upcoming Event Checkin Indicator

src/actions/authActions.ts, src/utils.ts
This reverts commit 93bc538555e3f2fd64c13a808cfb7765463eafdd.
=> Remove Census Popup

src/components/StorePage/index.tsx
=> Delay ACM Store Opening

.env.production
AWS backend available at:
https://api.acmucsd.com
https://membership-portal-api.app.acmucsd.com
Testing instance will be moved soon.
=> Change production API URL to AWS backend

.env.development, .env.production
I forgot about the testing instance URL. Here you go!
=> Change production & testing API URL to AWS backend (2.0!)

src/admin/adminActions.ts, src/auth/authActions.ts, src/event/eventActions.ts, src/leaderboard/leaderboardActions.ts, src/profile/profileActions.ts, src/types.ts, src/utils.ts
Resolves #406 
- adds ```fetchService``` to ```utils.ts``` as generic api handler
- adds type declaration file ```types.ts``` with relevant ```fetchService``` types
- replaces old fetch code in action files with ```fetchService```
=> Added generic api handler

src/admin/adminActions.ts, src/admin/components/CreateEventForm/index.tsx, src/admin/components/CreateEventForm/style.less, src/admin/components/EditEventForm/index.tsx, src/admin/components/EditEventForm/style.less, src/config.ts, src/utils.ts
Adds the ability to upload an event cover when creating or editing an event.
Resolves #361 and replaces #393.
=> Event Cover Upload

src/auth/components/SignInForm/index.tsx, src/auth/components/SignInForm/style.less, src/auth/containers/SignInForm.tsx, src/index.tsx
Resolves #387.
Add Yup schema to login form and implement respective errors for each potential
problem.
This follows the register form exactly, even down to CSS style. The only difference
is the Yup schema itself.
=> Create Form Validation for Login Flow

src/admin/containers/CreateEventForm.tsx, src/admin/containers/EditEventForm.tsx
URL's may occasionally contained mixed case, which
is not perfectly visualized. Ensure any detected URL's
are all made lowercase.
Resolves #424.
=> Lowercase detected URL's in Event forms

src/profile/components/ProfilePage/index.tsx
=> Added bios to user profile page

.eslintrc.js, src/profile/components/ProfilePage/index.tsx
=> seperate text with newlines for bio

src/auth/containers/PasswordPage.tsx
resolves #374 
Notifications seem to work already, the only issue was that the page refresh on form submit wasn't being handled.
=> Reset password notification

src/layout/components/Header/style.less, src/layout/components/HomePage/index.tsx, src/layout/components/HomePage/style.less, src/profile/components/ProfileCard/style.less
=> css housekeeping

src/profile/components/ProfilePage/index.tsx, src/profile/components/ProfilePage/style.less
=> fix: prevent bio from horizontally overflowing off of page

src/profile/components/ProfilePage/index.tsx
Fix a listing issue that was missed due to rebasing a recent PR (#443).
=> Fix Linting Issue

package.json, src/event/containers/PastEvents.tsx, src/layout/components/HomePage/style.less, src/leaderboard/containers/FourAndMore.tsx, src/utils.ts, yarn.lock
Used the JS filter function to filter events. I also made the timeframe variable into a var that can be accessed in the utils folder
=> Past events Time Filter

src/store/components/StorePage/index.tsx
I just realized I didn't bump the year when switching to winter quarter 😂 (I want it to be correct for the part of the winter kickoff slide I'm adding)
=> Wrong Year

src/index.tsx, src/store/components/AdminCollectionPage/index.tsx, src/store/components/AdminCollectionPage/style.less, src/store/components/StoreButton/index.tsx, src/store/components/StoreColorInput/index.tsx, src/store/components/StoreTextInput/index.tsx
Addresses #491 
Got the components there, but having issues with getting the data to show up / the submit button to work (unsure if I'm using Formik correctly).
Just making a draft PR for now to get some visibility, planning on working more on this later today/tom
=> Admin Collection Page

src/store/components/OrderPage/index.tsx, src/store/components/OrderPage/style.less, src/store/components/OrdersPage/index.tsx, src/store/components/OrdersPage/style.less
Addresses #490
alotta the data is missing though, @steets250 can you update the relevant be issue and link it here
=> added orders and order page

src/store/components/AdminItemPage/index.tsx, src/store/components/AdminItemPage/style.less, src/store/components/StoreCheckbox/index.tsx
"this will be good for your resume" - @steets250 
"At what cost" - @trulyronak
=> Added almost all of the fields for create item

src/admin/components/EditEventForm/index.tsx, src/admin/components/EditEventForm/style.less, src/types.ts
Addresses #428
Adds the current event image on the edit event page so that the upload button doesn't imply that no image has been added.
=> Admin: Edit Event Page 

src/store/components/ItemCard/index.tsx, src/store/components/ItemCard/style.less
=> Made the plus button smaller

src/store/components/AdminFulfillPage/index.tsx, src/store/components/AdminFulfillPage/style.less, src/store/containers/AdminFulfillPage.tsx
Some data is missing, but the functionality is mostly there
=> Add admin fulfill page

src/store/components/AdminPreparePage/index.tsx, src/store/components/AdminPreparePage/style.less, src/store/containers/AdminPreparePage.tsx, src/store/storeActions.ts
Issues (now added in #503)
- `PublicOrderItem` doesn't have
- an item name (so we use the uuid rn)
- a correct quantity (it always seems to be -1 in `item.option.quantity`)
- a user name (so we use the user uuid rn)
=> Added the admin prepare page

src/admin/components/AdminPage/index.tsx, src/config.ts, src/store/components/AdminPickupPage/index.tsx, src/store/components/AdminPickupPage/style.less, src/store/components/StoreImageUpload/index.tsx, src/store/containers/AdminPickupPage.tsx, src/store/storeActions.ts
Resolves #492.
I'm not using Yup, but this works just as well for now.
=> Create Admin Pickup Event Page

src/store/components/AdminFulfillPage/index.tsx, src/store/components/AdminPickupPage/index.tsx, src/store/components/AdminPreparePage/index.tsx, src/store/components/CheckoutPage/index.tsx, src/store/components/CheckoutPage/style.less, src/store/components/OrderPage/index.tsx
I added sorting by start date to pickup events, and then gave the checkout page its own style file so I could add a bottom margin. (Since the dropdown is absolutely positioned, there's no way for the page it's in to know how tall it is, so I just always add a bottom margin to avoid cutoff).
=> Checkout Page Updates

src/index.tsx, src/store/components/AdminFulfillPage/index.tsx, src/store/components/AdminFulfillPage/style.less, src/store/components/AdminPickupPage/index.tsx, src/store/components/AdminPreparePage/index.tsx, src/store/components/AdminQuantitiesPage/index.tsx, src/store/components/AdminQuantitiesPage/style.less, src/store/components/ItemPage/index.tsx, src/store/components/OrdersPage/index.tsx, src/store/components/StoreAdminPage/index.tsx, src/store/components/StorePage/index.tsx, src/store/containers/AdminPickupPage.tsx, src/store/containers/AdminQuantitiesPage.tsx, src/store/storeActions.ts
=> Store Todos

README.md
Resolves #57.
Also, we _could_ add a `CONTRIBUTING.md` at the same time as backend does for their documentation.
=> Update README versions and deploy guide

src/profile/components/ProfileCard/index.tsx, src/profile/components/ProfileCard/style.less
=> fix spacing

.github/auto_assign.yml
Modified the Github action workflow to assign current Portal UI members as reviewers for each other's code and assign the PR to its creator.
=> Update auto-assign workflow

src/admin/components/CreateEventForm/index.tsx, src/admin/components/EditEventForm/index.tsx
=> Fix Communities on Event Creation

src/store/components/ItemPage/index.tsx
=> Improve authorization for hidden store items

src/admin/components/CreateEventForm/index.tsx, src/admin/components/EditEventForm/index.tsx
- Add hack back to create event form
- Also add design so we can tag design events in the future
=> Add Hack as an ACM Community
