acmucsd/membership-portal-ui

src/containers/requireAuth.jsx, src/index.js
Redirects user if they aren't authenticated. However, screen still shows until they're redirected. We should return a redirection screen in the meantime.
=> Add requireAuth HOC

src/components/EventCheckIn/style.less
This one actually fixes the issue for Firefox. It does what I think was implicitly being done on Chrome
=> Firefox fix for button overflowing event check in module

src/components/LeaderListItem/style.less, src/components/PageLayout/style.less, src/components/ProfileCard/style.less, src/index.js
=> Profile Card and Content Padding Fixes

src/components/EventCard/index.jsx, src/components/EventCard/styles.less
The Ant Design progress ring doesn't align cleanly within its div, so I switched it to a static ring. It's now spaced an even 5% away from the top-right corner of the event card.
Resolves #202
=> Fix Event Points White Border

src/actions/eventsActions.js, src/containers/PastEvents.jsx
The PastEvents container was reversing the past events array in place on render. Rendering occurs twice on mobile browsers and this was causing the events array to flip twice and display in the wrong order. Switched to only reversing the array upon fetch so they maintain the same order for all cases with the most recent event on top.
Resolves #159
=> Maintain Proper Past Events Order

src/components/NavProfile/style.less
Problem was with how the browser treats content justification when using a flex box. Tested and working with Safari, Firefox, and Chrome.
Resolves #218
=> Fix Firefox Layout Issue

src/components/ProfileCard/index.jsx
Not sure if this is the best practice, but I used a history push rather than a link so the formatting retains Ant Design defaults for the card.
=> Change Profile Link to OnClick Event

package-lock.json, package.json, src/index.js, src/store.js
Closes #232.
Event calls are not necessary, since Heroku tracks membership portal events using dataclips.
=> Add Google Analytics

src/containers/UpcomingEvents.jsx, src/utils.js
Upcoming event cards display start and end time as well as the date.
Past events are omitted from this. Years are also removed from the event cards.
=> Event Card: Add event time to Upcoming cards

src/components/EventCard/styles.less
Right now, event card images have a ratio of 1.61. However, the event images have ratios of 1.77. I modified the sizing so that parts of the image don't get squeezed or cut off.
Resolved #293
=> Fix Event Card Image Ratio

.circleci/config.yml
Closes #280.
This adds a CircleCI job to automatically rebase the master branch whenever a commit is tagged using the standard SemVer format. If the tagged commit does not pass standard CI jobs (linting and testing), it will not be rebased to master.
Tags that trigger the rebase job are of the format: `vXX.XX.XX[-keyword]`
The keyword part is optional.
=> CircleCI Automatic Rebase

src/reducers/UserReducer.ts
Resolves #320.
This PR adds the user's store credits to the user store and reducer. The API lists the store credits of a user under their model, in the property "credits".
This can be found under the [User database model file:](https://github.com/acmucsd/membership-portal/blob/dcb4e4d30e3296285e874a132e83e24a3233ed7a/src/db/models/user.js#L150-L153)
```js
module.exports = (Sequelize, db) => {
const User = db.define('User', {
id: {
type: Sequelize.INTEGER,
primaryKey: true,
autoIncrement: true,
},
// --->8---    
// spendable store credits, 1 exp point = 100 store credits
credits: {
type: Sequelize.INTEGER,
defaultValue: 0,
},  
// --->8---
```
Testing the API route as well, we can also see that a seeded *test instance* account has 100 times its membership points as credits. You may try …
=> Add "credits" property to User state

src/actions/authActions.ts, src/containers/requireAuth.tsx
The notification "Please sign in or register for an account before continuing." will now only pop up if someone attempts to visit any location except for "/" without being signed in. This fixes the annoyance introduced by the check-in PR. I know the solution is a bit messy, but this is due to the action being nested weirdly. I'm going to look into cleaning up the actions as a future task to neaten things up.
=> Remove Authentication Alert for Base URL

package-lock.json, package.json, src/components/EventCard/index.tsx
All images on Event Cards are now lazy-loaded using external package.
This change bumps the average load time of home page from 7.29 seconds down to
1.94 seconds, which is a massive difference. Here are screenshots from the
Firefox Developer Tools showing the difference in loading times before the
lazy-load change:
And after it:
While the images still require loading when rendered, the initial loading shock
is not as large. However, important to note that the actual image sizes should
be reduced down from 1080p, as that resolution is wasteful for the size of the
images used.
The resolution change is either mandated by the backend, or can be done with an
external script uploading old event cards to an S3 bucket at a downscaled
resolution and updating existing events using it.
=> Add lazy-loading to Event Card images

src/utils.ts
This PR adds some additional placeholders for ranks. They are more or less designed as cheeky placeholders until we come up with some better rank names.
We additionally fix the issue with overflowing the rank by editing the formula, since we wouldn't account
for 0-indexing.
=> Add additional ranks

.env.development, .env.production, netlify.toml, package-lock.json, package.json, src/config.ts
This PR adds the configuration necessary for Netlify to
deploy development builds for previews and branches such as
`nightly`, branches off of `nightly` and deploy previews for
PR's.
Note that this PR uses `dotenv` to deploy environment variables
instead of `cross-env`, and I haven't tested `dotenv` on Windows.
If this ends up not working on Windows, I can change everything back
to `cross-env`.
=> Add Netlify configuration for Test Deploy Previews

src/actions/eventsActions.ts
Past events endpoint now defaults to reversing the order, so no need to reverse here.
=> Don't unnecessarily reverse past events

src/admin/containers/CreateEventForm.tsx, src/admin/containers/EditEventForm.tsx
URL's are not rendered in the Event card due to the internal "Location"
value occasionally containing trailing whitespace and tripping the regex
for URL's. Trim whitespace on "Location" value before submitting a
"Create Event" or "Edit Event" form.
=> Trim whitespace for "Location" in Event forms

src/admin/components/CreateEventForm/index.tsx, src/admin/components/CreateEventForm/style.less, src/admin/components/EditEventForm/index.tsx, src/admin/components/EditEventForm/style.less, src/admin/containers/CreateEventForm.tsx, src/admin/containers/EditEventForm.tsx
Resolves #421.
Forms for creating and editing events use simple `if` statements
as opposed to a Yup schema, which is a standard. Refactor form errors
to use Yup schema for CreateEventForm and EditEventForm.
=> Add Yup Schema for Event Creation and Editing Flow

src/profile/components/ProfilePage/index.tsx, src/profile/components/ProfilePage/style.less
- empty lines properly form line breaks
```
a
b
```
- bios consisting of all line break/whitespace properly recognized as empty
```
```
=> fix: improved bio whitespace handling

.github/auto_assign.yml, .github/workflows/assign_reviewers_to_new_pr.yml, .github/workflows/label_ready_pr_to_merge.yml
Workflow for Dev Team involved adding or removing "PR" labels depending on stage
in approval process. Automate this workflow using GitHub Actions, modifying labels
whenever PR is fully approved.
Also add action to automatically assign at least two reviewers to PR.
=> Add GitHub Actions to manage PR labels

package.json, src/admin/components/CreateEventForm/index.tsx, src/admin/components/EditEventForm/index.tsx, yarn.lock
resolves #425 
Uses `antd-img-crop` to provide 16:9 cropping modal for admin event cover uploads.
=> Event cover resizing

src/layout/components/NavBarHorizontal/index.tsx, src/layout/components/NavBarVertical/index.tsx, src/leaderboard/components/LeaderListItem/index.tsx, src/leaderboard/components/TopLeaderCard/index.tsx, src/leaderboard/containers/FourAndMore.tsx, src/leaderboard/containers/TopThree.tsx, src/profile/components/ProfileUpdate/index.tsx
Couple small profile improvements:
- The discard button on the edit profile page redirects to the profile page.
- The profile item in the nav bar only highlights when the user profile is viewing their own profile.
- If a user selects themself in the leaderboard, it takes them to the profile page, not their public profile.
Resolves #407.
=> Profile Routing Improvements

src/admin/adminActions.ts, src/admin/components/EditEventForm/index.tsx
The logic for checking if an event was deleted was outdated since the number of deleted events is no longer sent by the backend. In addition, the notification for that particular route was duplicated between the api function and the actual api call.
Resolves #447.
=> Fix Delete Event Logic

src/event/components/EventCard/styles.less
Long URL's or locations overflow off of the event card and
do not display. Clip them by overflowing them with an ellipsis.
=> Clip long URL's in EventCard field

src/profile/components/ProfileUpdate/index.tsx, src/profile/containers/ProfileUpdate.tsx, src/profile/profileActions.ts
resolves #198, resolves #412, resolves #433
Updates profile picture URL after user profile has been fetched. Avatar was using a stale value before (the initial profile picture from redux store).
=> Update profile picture URL on fetch

src/event/containers/PastEvents.tsx, src/event/eventActions.ts, src/event/eventReducer.ts, src/event/eventTypes.ts, src/leaderboard/containers/FourAndMore.tsx, src/leaderboard/containers/TopThree.tsx, src/leaderboard/leaderboardActions.ts, src/leaderboard/leaderboardReducer.ts, src/leaderboard/leaderboardTypes.ts
Resolves #469.
Fix persistence issue by adding `timeframe` state parameter to Redux store, so parameter persists across component unloads. Both Past Events and Leaderboard are fixed, as they use a similar mechanic.
=> Add persistence to filters for Past Events and Leaderboard

src/store/components/ItemPage/index.tsx, src/store/components/NavigationBar/index.tsx, src/store/storeActions.ts, src/store/storeReducer.ts, src/types.ts
The store cart now contains objects with the structure `{ item: PublicMerchItem; optionUUID: string; quantity: number; }`, so that the `CartDisplay` component can pull the item data locally, rather than needing to call an API route to retrieve the cart.
=> Cart Restructure

src/store/components/ItemPage/index.tsx, src/store/components/OptionSelector/index.tsx, src/store/storeReducer.ts, src/types.ts
This PR refactors `CartItem` and `state.store.cart` (Redux store) to hold `PublicMerchItemOption` and all of the relevant metadata instead of the just the option UUID. Storing option UUIDs made sense when used in conjunction with the [`getCart` endpoint ](https://github.com/acmucsd/membership-portal/pull/209) but since we're storing the entire cart metadata on the client-side, it makes more sense to fill the Redux store with that metadata as well. It also makes it more convenient for the `CartDisplay` as the option metadata doesn't need to be unnecessarily searched for.
The store reducer and client dispatcher (`ItemPage`) have been updated to reflect these changes. `OptionSelector` has also been refactored to support this change with some extensibility and type safety tweaks.
=> Cart updates

src/store/components/AdminFulfillPage/index.tsx, src/store/components/StoreImageUpload/index.tsx
=> Added Modal for the fulfill orders page

src/layout/components/PageLayout/index.tsx, src/layout/components/PageLayout/style.less, src/profile/components/ProfileCard/style.less
There was a class name overlap between the `PageLayout` selector and the profile cart class name, this rename resolves that issue as a quick fix.
=> Rename PageLayout Selector

src/auth/authActions.ts, src/auth/containers/requireAdminAuth.tsx
If the user attempts to access a portal link directly and isn't signed in, they're redirected to the login page. After logging in, they're taken to the home page, rather than their previously desired destination. The `verifyToken` route now encodes the destination into the login URL, so that upon login, the user is taken to the correct destination.
=> Update loginUser Action

src/store/components/OrderPage/index.tsx
In order to determine that the current time is too close to the pickup event, the current time should be greater than the pickup start time minus two days, not less than.
=> Fix Incorrect Date Comparison

package.json, src/auth/authActions.ts, src/auth/containers/RegisterForm.tsx, src/auth/containers/SignInForm.tsx, src/auth/containers/requireAdminAuth.tsx, src/auth/containers/requireAuth.tsx, src/auth/containers/requireStoreAccess.tsx, src/event/containers/CheckInHandler.tsx, src/history.ts, src/index.tsx, src/redux_reducers.ts, src/redux_store.ts, src/store/components/AdminCollectionPage/index.tsx, src/store/components/AdminItemPage/index.tsx, src/store/components/AdminPickupPage/index.tsx, src/store/components/CheckoutPage/index.tsx, src/store/containers/CartPage.tsx, yarn.lock
History management has now been pulled out of the Redux state. It looks like history was added in to allow for page navigation via Redux dispatches, but that's never something that was implemented and just added to boilerplate code. There's now a `history.ts` file that can be imported wherever a `history.push` or `history.replace` is needed outside of a component. For usages inside of a component, `useHistory` or `useLocation` can continue to be used. This removes the need for the `connected-react-router` package, as our router is now state independent.
=> Independent History

src/leaderboard/components/LeaderPage/index.tsx, src/leaderboard/leaderboardReducer.ts
Rather than showing "No users found for this timeframe!" while initially populating leaderboard data, the portal now displays "Loading users...".
=> Update Leaderboard Loading Messages

src/event/components/EventCard/index.tsx, src/layout/components/PageLayout/index.tsx
This PR fixes two separate bugs.
1: External URLs are not always prefixed with https:// so they sometimes will not properly redirect. Fixed with existing utility function to deal with this.
2: The breakpoint at 768px was inconsistent on the navbar and resulted in two shifts at 767px and 768px rather than a single shift.
=> fix external url redirect and breakpoint

src/auth/utils.ts
There was an issue where there was a stray double function, so calling the helper function to reset a user's password was only generating a function and wasn't actually executing the call.
Resolves #566
=> Fix Password Reset API Call

src/store/containers/AdminFulfillPage.tsx, src/store/containers/AdminPickupPage.tsx, src/store/containers/AdminPreparePage.tsx, src/store/utils.ts, src/types.ts
Previously, store admins were only shown currently ongoing and future pickup events in the dropdown for store fulfillment. However, this meant that a pickup event disappeared as soon as it was over, so if it hadn't already been marked as complete, then someone from dev needed to find its uuid and manually access the page. The dropdown condition is now changed to display both past and future pickup events that have a status of active, which will allow admins to both fulfill orders and mark pickup events as complete even after their original time window has passed.
=> Update Store Admin Pickup Dropdown Conditions

src/event/components/EventCheckIn/style.less, src/layout/components/HomePage/style.less, src/profile/components/ProfileCard/style.less, src/styles/vars.less
Redo #584 after the rollback. Cards now have a minimum width and flex into 2 lines instead of overflowing.
=> Redo dashboard card responsiveness

src/store/components/ItemPage/index.tsx
Fixed bug preventing add to cart functionality from working due to issue in incorrect mapDispatchToprops function because addToCart was undefined.
Expected behavior to test for:
- Add to Cart works correctly now
- Hidden item url redirect for non-store admins (Previous PR change)
=> Fix Add to Cart Broken Functionality

src/store/components/AdminItemPage/index.tsx
Bug was caused by admin page mapping variant options directly without matching the position from the metadata options
=> Fix bug where store item variants are not sorted 

src/index.tsx
Renames client-side routes to match email template from the backend.
Since these routes can only be hit from a direct email link, they aren't linked anywhere else in the codebase that I need to tweak.
=> Fix route naming consistency

src/admin/components/CreateEventForm/index.tsx
This PR addresses the bug found in Issue #615 
To reset the preview when an event form is created, the state of `fileList` when uploading is being kept track of. When the whole form is submitted the `fileList` becomes empty and the preview will dissapear.
=> Fixing Event Cover Image Not Clearing

src/store/components/AdminItemPage/index.tsx, src/store/components/CartDisplay/index.tsx, src/store/components/ItemCard/index.tsx, src/store/components/ItemPage/index.tsx, src/types.ts, src/utils.tsx
- hello 
- i am not on call for this
=> make compatible with multiple store gallery images
